modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
issueTrackerURL = "https://github.com/KVdz00/keybindplus/issues"

[[mods]]
modId = "keybindplus"
version = "${version}"
displayName = "KeybindPlus"
description = "Keybind profile manager for PvP & modded Minecraft players. Save, load, compare, and share keybind profiles."
authors = "KVdz00"
displayURL = "https://github.com/KVdz00/keybindplus"
logoFile = "icon.png"

[[dependencies.keybindplus]]
modId = "forge"
type = "required"
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keybindplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.17, 1.18)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keybindplus]]
modId = "architectury"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"
