modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/KVdz00/keybindplus/issues"

[[mods]]
modId = "keybindplus"
version = "${version}"
displayName = "KeybindPlus (Beta)"
description = "[EXPERIMENTAL BETA] Keybind profile manager for Minecraft 1.19.x (Fabric & Forge). Save, load, compare, and edit keybind profiles."
authors = "KVdz00"
displayURL = "https://github.com/KVdz00/keybindplus"
logoFile = "icon.png"

[[dependencies.keybindplus]]
modId = "forge"
type = "required"
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keybindplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.19, 1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keybindplus]]
modId = "architectury"
type = "required"
versionRange = "[6,)"
ordering = "NONE"
side = "BOTH"
